=== eagletrt/telemetria-sender/models/config.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://eagletrt.it/eagletrt-telemetria-chimera/config.schema.json",
    "title": "Config Json",
    "description": "v1.0 - 2020-10-08 / Schema for the Json config of eagletrt-telemetria-chimera.",

    "definitions": {
        "boolean-integer": {
            "type": "integer",
            "enum": [0, 1]
        },
        "port": {
            "type": "integer",
            "minimum": 1,
            "maximum": 65535
        },
        "host": {
            "type": "string"
        },
        "simple-string": {
            "type": "string",
            "maxLength": 255,
            "pattern": "^[a-zA-Z0-9 \\-_.~!*'();:@&=+$,\\/?#\\[\\]]*$"
        },
        "strings-set": {
            "type": "array",
            "uniqueItems": true,
            "items": {
                "type": "string"
            }
        }
    },

    "type": "object",
    "properties": {
        "mqtt": {
            "description": "Mqtt configuration object",
            "type": "object",
            "properties": {
                "host": {
                    "description": "Host of mqtt server",
                    "default": "localhost",
                    "$ref": "#/definitions/host"
                },
                "port": {
                    "description": "Port of mqtt server",
                    "default": 1883,
                    "$ref": "#/definitions/port"
                },
                "data_topic": {
                    "description": "Topic used to send mqtt data documents",
                    "default": "telemetria",
                    "$ref": "#/definitions/simple-string"
                },
                "log_topic": {
                    "description": "Topic use to send mqtt log lines",
                    "default": "telemetria_log",
                    "$ref": "#/definitions/simple-string"
                }
            },
            "additionalProperties": false
        },
        "mongodb": {
            "description": "MongoDB configuration object",
            "type": "object",
            "properties": {
                "host": {
                    "description": "Host of the mongodb server",
                    "default": "localhost",
                    "$ref": "#/definitions/host"
                },
                "port": {
                    "description": "Port of the mongo server",
                    "default": "27017",
                    "$ref": "#/definitions/port"
                },
                "db": {
                    "description": "MongoDB database's name",
                    "default": "eagle_test",
                    "$ref": "#/definitions/simple-string"
                },
                "collection": {
                    "description": "MongoDB collection's name",
                    "default": "chimera",
                    "$ref": "#/definitions/simple-string"
                }
            },
            "additionalProperties": false
        },
        "gps": {
            "description": "GPS configuration object",
            "type": "object",
            "properties": {
                "plugged": {
                    "description": "Whether the gps is plugged in",
                    "default": 1,
                    "$ref": "#/definitions/boolean-integer"
                },
                "simulated": {
                    "description": "Whether the gps is simulated",
                    "default": 1,
                    "$ref": "#/definitions/boolean-integer"
                },
                "interface": {
                    "description": "Interface of the simulated gps' serial port",
                    "default": "/dev/pts/4",
                    "$ref": "#/definitions/simple-string"
                }
            },
            "additionalProperties": false
        },
        "pilots": {
            "description": "List of the pilots' names",
            "default": [
                "default",
                "Ivan",
                "Filippo",
                "Mirco",
                "Nicola",
                "Davide"
            ],
            "$ref": "#/definitions/strings-set"
        },
        "races": {
            "description": "List of the types of races",
            "default": [
                "default",
                "Autocross",
                "Skidpad",
                "Endurance",
                "Acceleration"
            ],
            "$ref": "#/definitions/strings-set"
        },
        "circuits": {
            "description": "List of the circuits",
            "default": [
                "default",
                "Vadena",
                "Varano",
                "Povo"
            ],
            "$ref": "#/definitions/strings-set"
        },
        "can_interface": {
            "description": "Name of the can interface",
            "default": "can0",
            "type": "string"
        },
        "sending_rate": {
            "description": "Sending rate in milliseconds",
            "default": 500,
            "type": "integer",
            "minimum": 0
        },
        "verbose": {
            "description": "Whether debug logs will be printed",
            "default": 0,
            "$ref": "#/definitions/boolean-integer"
        }
    },
    "additionalProperties": false
  }

=== eagletrt/telemetria-sender/config.json
{
  "mqtt": {
    "host": "localhost",
    "port": 1883,
    "data_topic": "telemetria",
    "log_topic": "telemetria_log"
  },
  "mongodb": {
    "host": "localhost",
    "port": 27017,
    "db": "eagle_test",
    "collection": "merda"
  },
  "gps": {
    "plugged": 1,
    "simulated": 0,
    "interface": "/home/gps0"
  },
  "pilots": [
    "default",
    "Ivan",
    "Filippo",
    "Mirco",
    "Nicola",
    "Davide"
  ],
  "races": [
    "default",
    "Autocross",
    "Skidpad",
    "Endurance",
    "Acceleration"
  ],
  "circuits": [
    "default",
    "Vadena",
    "Varano",
    "Povo"
  ],
  "can_interface": "can0",
  "sending_rate": 500,
  "verbose": 0
}
